version: '3.7'
services:
        mysql:
                image: mysql:8.0
                ports:
                        - 3309:3306
                environment:
                        MYSQL_ROOT_PASSWORD: oracletest
                volumes:
                        - ./mysql:/var/lib/mysql


        adminer:
                image: adminer:4.7.8
                restart: unless-stopped
                ports:
                        - 3310:8080
                depends_on:
                        - mysql
